CREATE DATABASE OneToOne

CREATE TABLE Passports(
PassportID INT NOT NULL,
PassportNumber CHAR(8) NOT NULL
)

ALTER TABLE Passports
ADD CONSTRAINT pk_PassportID 
PRIMARY KEY (PassportID)

INSERT INTO Passports
VALUES (101, 'N34FG21B'),
		(102, 'K65LO4R7'),
		(103, 'ZE657QP2')

CREATE TABLE Persons(
PersonID INT IDENTITY,
FirstName VARCHAR(30) NOT NULL,
Salary REAL NOT NULL,
PassportID INT NOT NULL
)

ALTER TABLE Persons
ADD CONSTRAINT pk_PersonsID
PRIMARY KEY (PersonID)

ALTER TABLE Persons
ADD CONSTRAINT fk_Persons_Passports
FOREIGN KEY (PassportID)
REFERENCES Passports

INSERT INTO Persons
VALUES ('Roberto', 43300.00, 102),
		('Tom', 56100.00, 103),
		('Yana', 60200.00, 101)