CREATE DATABASE OnlineStoreDatabase

CREATE TABLE Cities(
	CityID INT PRIMARY KEY NOT NULL,
	Name VARCHAR(30) NOT NULL
)

CREATE TABLE Customers(
	CustomerID INT PRIMARY KEY NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT NOT NULL,
	FOREIGN KEY (CityID) REFERENCES Cities
)

CREATE TABLE Orders(
	OrderID INT PRIMARY KEY NOT NULL,
	CustomerID INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Customers
)

CREATE TABLE ItemTypes(
	ItemTypeID INT PRIMARY KEY NOT NULL,
	Name VARCHAR(30) NOT NULL
)

CREATE TABLE Items(
	ItemID INT PRIMARY KEY NOT NULL,
	Name VARCHAR(30) NOT NULL,
	ItemTypeID INT NOT NULL,
	FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes
)

CREATE TABLE OrderItems(
	OrderID INT NOT NULL, 
	ItemID INT NOT NULL,
	FOREIGN KEY (OrderID) REFERENCES Orders,
	FOREIGN KEY (ItemID) REFERENCES Items,
	CONSTRAINT PK_OrderItem
	PRIMARY KEY (OrderID, ItemID)
)